// Splits the official Acopia wordmark (public/brand/acopia-logo-primary.svg, from
// https://acopia.co.uk/wp-content/uploads/2024/12/acopia-logo-primary.svg) into its nine vector shapes and writes
// lib/logo.ts, so the preloader and header can draw and animate each letter. Run with `npm run logo`.
import { readFileSync, writeFileSync } from "node:fs";

const svg = readFileSync("public/brand/acopia-logo-primary.svg", "utf8");
const viewBox = svg.match(/viewBox="([^"]+)"/)[1];
const paths = [...svg.matchAll(/<path[^>]*d="([^"]+)"/g)].map((m) => m[1].replace(/\s+/g, " ").trim());
// File order of the shapes in the Illustrator export, named by what they draw.
const names = ["c", "a", "o", "p", "i-dot", "i", "a2", "reg-ring", "reg-r"];
if (paths.length !== names.length) throw new Error(`expected ${names.length} shapes, found ${paths.length}`);
const parts = paths.map((d, i) => ({ id: names[i], d, x: Number(d.match(/^M([\d.]+)/)[1]) }));
// Reading order (left to right by first point) so the preloader can set the letters in sequence.
const order = ["a", "c", "o", "p", "i", "i-dot", "a2", "reg-ring", "reg-r"];
const out = `// Generated by scripts/logo.mjs from the official wordmark. Do not edit by hand.
export const logoViewBox = ${JSON.stringify(viewBox)};
export type LogoPart = { id: string; d: string };
// Letters in reading order; "i-dot" follows its stem and the registered mark comes last.
export const logoParts: LogoPart[] = ${JSON.stringify(order.map((id) => { const p = parts.find((q) => q.id === id); return { id, d: p.d }; }), null, 2)};
`;
writeFileSync("lib/logo.ts", out);
console.log(parts.map((p) => `${p.id} starts x=${p.x}`).join("\n"));
